

#VIVO转换文件路径
rootpath: D

#上传文件到服务器的目录位置
uploadFilePath: /Users/shoushinsakai/Desktop/uploadTest/
#uploadFilePath: C:/Users/Administrator/Desktop/files/

spring:
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://122.152.216.95:3306/security?useUnicode=true&characterEncoding=UTF-8&connectTimeout=60000&socketTimeout=60000&autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false
    username: root
    password: Zhenyu7.16
    druid:
      initial-size: 3
      min-idle: 1
      max-active: 20
      max-wait: 60000


  redis:
    database: 0
    host: 47.98.131.254
    port: 6379
    password: 123456
    timeout: 3000

server:
  port: 8091
logging:
  level:
    com.boot.dao.mapper: debug
#mybatis:
#  config-location: classpath*:mapper/*.xml
#  config-location: classpath:mapper/*.xml
#  mapper-locations: classpath:mapper/*.xml
#  config-location:



